name: Pull Request
on: pull_request

jobs:
  os_matrix:
    strategy:
     matrix:
       os: [ubuntu-latest, windows-latest]
  build:
    name: build & tests
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Build & Test 
      run: ./build.sh Tests