name: Release
on:
  release:
    types: [ created ]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Pack & Publish
        run: ./build.sh Pack Publish --api-key ${{secrets.NUGET_TOKEN}}
      - uses: actions/upload-artifact@v1
        with:
          name: packages
          path: artifacts/packages